[package]
name = "frost"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
secp256k1-math = { git = "https://github.com/Trust-Machines/rust-secp256k1-math", rev = "3b9fe0c8f95c53f7068d980fac38dc00ecf784cd"  }
hashbrown = "0.12"
hex = "0.4.3"
num-traits = "0.2"
polynomial = "0.2.4"
rand_core = "0.5"
sha3 = "0.10.5"

[lib]
path = "src/lib.rs"    # The source file of the target.
crate-type = ["lib"]   # The crate types to generate.

[[bin]]
name = "frost"
path = "src/main.rs"
