[package]
name = "frost"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
curve25519-dalek = { git = "https://github.com/xoloki/curve25519-dalek" }
hex = "0.4.3"
num-traits = "0.2"
polynomial = "0.2.4"
rand_core = "0.5"
sha3 = "0.10.5"
