[package]
name = "frost"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
secp256k1-math = { git = "https://github.com/Trust-Machines/rust-secp256k1-math", rev = "64c7b5e8fb01fb1ac770de89651af7ba1609ba79" }
hex = "0.4.3"
num-traits = "0.2"
polynomial = "0.2.4"
rand_core = "0.5"
sha3 = "0.10.5"
